
export const breadcrumbNames = {
    mainEntry: {menu: '1', meta: ['']},
    personal: {menu: '2', meta: ['小玩意']},
    drawDice: {menu: '2-1', meta: ['小玩意', '骰子作图']},
    randomSelect: {menu: '2-2', meta: ['小玩意', '随机抽人']},
    calculator: {menu: '2-3', meta: ['小玩意', '计算器']},
    littleFunc: {menu: '3', meta: ['小功能']},
    cmd: {menu: '3-1', meta: ['小功能', 'cmd指令大全']},
    weatherQuery: {menu: '3-2', meta: ['小功能', '天气查询']},
};


export const dice = [
    [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
    ],
    [
        [0, 0, 0],
        [0, 1, 0],
        [0, 0, 0],
    ],
    [
        [0, 0, 1],
        [0, 0, 0],
        [1, 0, 0],
    ],
    [
        [0, 0, 1],
        [0, 1, 0],
        [1, 0, 0],
    ],
    [
        [1, 0, 1],
        [0, 0, 0],
        [1, 0, 1],
    ],
    [
        [1, 0, 1],
        [0, 1, 0],
        [1, 0, 1],
    ],
    [
        [1, 0, 1],
        [1, 0, 1],
        [1, 0, 1],
    ],
    [
        [1, 0, 1],
        [1, 1, 1],
        [1, 0, 1],
    ],
    [
        [1, 1, 1],
        [1, 0, 1],
        [1, 1, 1],
    ],
    [
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
    ],
];

export const weatherImgMap = {
    "晴": `./sunny.jpg`,
    "少云": `./cloudy.jpg`,
    "晴间多云": `./sunny.jpg`,
    "多云": `./cloudy.jpg`,
    "阴": `./overcast.jpg`,
    "有风": `./windy.jpg`,
    "平静": `./windy.jpg`,
    "微风": `./windy.jpg`,
    "和风": `./windy.jpg`,
    "清风": `./windy.jpg`,
    "强风/劲风": `./windy.jpg`,
    "疾风": `./windy.jpg`,
    "大风": `./windy.jpg`,
    "烈风": `./windy.jpg`,
    "风暴": `./typhoon.jpg`,
    "狂爆风": `./typhoon.jpg`,
    "飓风": `./storm.jpg`,
    "热带风暴": `./typhoon.jpg`,
    "阵雨": `./rainy.jpg`,
    "雷阵雨": `./rainy.jpg`,
    "雷阵雨并伴有冰雹": `./snow and rain.jpg`,
    "小雨": `./rainy.jpg`,
    "中雨": `./rainy.jpg`,
    "大雨": `./heavyRain.jpg`,
    "暴雨": `./heavyRain.jpg`,
    "大暴雨": `./heavyRain.jpg`,
    "特大暴雨": `./heavyRain.jpg`,
    "强阵雨": `./heavyRain.jpg`,
    "强雷阵雨": `./heavyRain.jpg`,
    "极端降雨": `./rainy.jpg`,
    "毛毛雨/细雨": `./rainy.jpg`,
    "雨": `./rainy.jpg`,
    "小雨-中雨": `./rainy.jpg`,
    "中雨-大雨": `./heavyRain.jpg`,
    "大雨-暴雨": `./heavyRain.jpg`,
    "暴雨-大暴雨": `./heavyRain.jpg`,
    "大暴雨-特大暴雨": `./heavyRain.jpg`,
    "雨雪天气": `./snow and rain.jpg`,
    "雨夹雪": `./snow and rain.jpg`,
    "阵雨夹雪": `./snow and rain.jpg`,
    "冻雨": `./snow and rain.jpg`,
    "雪": `./snowy.jpg`,
    "阵雪": `./snowy.jpg`,
    "小雪": `./snowy.jpg`,
    "中雪": `./snowy.jpg`,
    "大雪": `./snowy.jpg`,
    "暴雪": `./snowy.jpg`,
    "小雪-中雪": `./snowy.jpg`,
    "中雪-大雪": `./snowy.jpg`,
    "大雪-暴雪": `./snowy.jpg`,
    "浮尘": `./sandy.jpg`,
    "扬沙": `./sandy.jpg`,
    "沙尘暴": `./sandy.jpg`,
    "强沙尘暴": `./sandy.jpg`,
    "龙卷风": `./storm.jpg`,
    "雾": `./foggy.jpg`,
    "浓雾": `./foggy.jpg`,
    "强浓雾": `./foggy.jpg`,
    "轻雾": `./foggy.jpg`,
    "大雾": `./foggy.jpg`,
    "特强浓雾": `./foggy.jpg`,
    "霾": `./foggy.jpg`,
    "中度霾": `./foggy.jpg`,
    "重度霾": `./foggy.jpg`,
    "严重霾": `./foggy.jpg`,
    "热": `./sunny.jpg`,
    "冷": `./snowy.jpg`,
    "未知": `./unknown.jpg`,
};





